"use client";
import Image from "next/image"; import Link from "next/link"; import { useRef, useState } from "react"; import { media, mediaUsages } from "@/content/registry"; import type { MediaAsset } from "@/lib/types"; import { CopyLink } from "./ui";
export function GalleryBrowser() {
  const [filter, setFilter] = useState("all"); const [selected, setSelected] = useState<MediaAsset>(); const dialog = useRef<HTMLDialogElement>(null);
  const filters = [["all", "Все"], ["image", "Изображения"], ["youtube", "Видео"], ["cover", "Обложки"], ["issue", "Выпуск"], ["material", "Материал"], ["person", "Люди"], ["2026", "2026"]];
  const shown = media.filter((m) => filter === "all" || m.type === filter || m.kind === filter || m.createdAt.startsWith(filter) || (filter === "issue" && m.tags.includes("выпуск")));
  function open(item: MediaAsset) { setSelected(item); dialog.current?.showModal(); }
  return <><div className="filters" aria-label="Фильтры галереи">{filters.map(([v, l]) => <button aria-pressed={filter === v} onClick={() => setFilter(v)} key={v}>{l}</button>)}</div><div className="gallery-grid">{shown.map((m) => <button onClick={() => open(m)} key={m.id}>{m.src ? <Image src={m.src} alt={m.alt} width={700} height={500} /> : <Image src={m.thumbnail!} alt={m.alt} width={700} height={500} unoptimized />}<span>{m.title}<small>{m.type === "youtube" ? "Видео" : m.kind}</small></span></button>)}</div><dialog className="media-dialog" ref={dialog} onClick={(e) => e.target === dialog.current && dialog.current?.close()}>{selected && <><button className="dialog-close" onClick={() => dialog.current?.close()} aria-label="Закрыть">×</button><div className="media-preview">{selected.src ? <Image src={selected.src} alt={selected.alt} width={1200} height={800} /> : <Image src={selected.thumbnail!} alt={selected.alt} width={1000} height={700} unoptimized />}</div><div className="media-details"><span className="eyebrow">{selected.type}</span><h2>{selected.title}</h2><p>{selected.description}</p><dl><dt>Автор</dt><dd>{selected.author}</dd><dt>Источник</dt><dd>{selected.source}</dd><dt>Лицензия</dt><dd>{selected.license}</dd></dl><h3>Используется</h3>{mediaUsages(selected.id).map((u) => <Link key={u.url} href={u.url}>{u.label} →</Link>)}<div className="button-row"><Link href={`/media/${selected.id}`}>Постоянная страница</Link><CopyLink url={`/media/${selected.id}`} />{selected.downloadable && selected.src && <a download href={selected.src}>Скачать</a>}</div></div></>}</dialog></>;
}
